import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  appBg: { backgroundColor: "#fff" },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  logoImage: {
    width: 220,
    height: 120,
    marginBottom: 20,
  },
  title: { fontSize: 32, fontWeight: "700", marginBottom: 8 },
  subtitle: { fontSize: 14, color: "#444", marginBottom: 16 },
  themeNotice: { fontSize: 14, color: "#333", marginBottom: 4 },
  themeNoticeSecondary: { fontSize: 12, color: "#4b5563", marginBottom: 16 },
  themeRow: { flexDirection: "row", marginBottom: 20 },
  themeBtn: {
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    marginHorizontal: 6,
    backgroundColor: "#fff",
  },
  themeBtnActiveKakao: {
    borderColor: "#F2C94C",
    backgroundColor: "#FFF7DA",
  },
  themeBtnActiveIos: {
    borderColor: "#0A84FF",
    backgroundColor: "#E7F2FF",
  },
  primaryBtn: {
    backgroundColor: "#F2C94C",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    marginTop: 12,
    alignSelf: "center",
  },
  primaryBtnText: { fontWeight: "700" },
  kakaoBg: { backgroundColor: "#FFF8E6" },
  iosBg: { backgroundColor: "#fff" },
  kakaoTitle: { color: "#3C1E00" },
  iosTitle: { color: "#0A84FF" },
  loginBox: { padding: 20, marginTop: 60 },
  loginBoxIos: {
    borderRadius: 24,
    marginHorizontal: 24,
    padding: 24,
    backgroundColor: "#fff",
    shadowColor: "#0A84FF",
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  loginTitle: { fontSize: 28, fontWeight: "700", marginBottom: 12 },
  input: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  hint: { fontSize: 12, color: "#666", marginBottom: 10 },
  linkBtn: { marginTop: 10, alignItems: "center" },
  appHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  appHeaderTitle: { fontSize: 20, fontWeight: "700" },
  smallBtn: { padding: 8 },
  content: { flex: 1 },
  friendRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: { fontWeight: "700" },
  avatarLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  friendInfo: { flex: 1 },
  friendName: { fontWeight: "700", fontSize: 16 },
  friendSubtitle: { color: "#6b7280", fontSize: 13 },
  profileTag: { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  userRow: { backgroundColor: "#fff5e5" },
  chatRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#f3f4f6",
  },
  chatHint: { color: "#9ca3af", fontSize: 12, marginTop: 2 },
  tabBar: {
    height: 64,
    borderTopWidth: 1,
    borderColor: "#eee",
    flexDirection: "row",
  },
  tabItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabActive: { color: "#111", fontWeight: "700" },
  settingsBox: { padding: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 4 },
  settingDescription: { color: "#6b7280", marginBottom: 10 },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  settingLabel: { fontWeight: "600" },
  secondaryBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#0A84FF",
    backgroundColor: "#fff",
    marginTop: 8,
  },
  secondaryBtnText: { color: "#0A84FF", fontWeight: "600" },
  modalContainer: { flex: 1, backgroundColor: "#fff" },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  modalTitle: { fontSize: 18, fontWeight: "700" },
  closeBtn: { padding: 8 },
  managementHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  managementHeaderActions: { flexDirection: "row", alignItems: "center" },
  managementList: { padding: 16 },
  managementRow: {
    borderBottomWidth: 1,
    borderColor: "#eee",
    paddingVertical: 12,
    paddingHorizontal: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  managementActionGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  managementActionBtn: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 10,
    marginLeft: 8,
    minWidth: 96,
  },
  managementEditBtn: {
    borderColor: "#0A84FF",
    backgroundColor: "#fff",
  },
  managementDeleteBtn: {
    borderColor: "#f87171",
    backgroundColor: "#fee2e2",
  },
  managementActionText: {
    fontWeight: "600",
    color: "#111",
  },
  profileActionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  deleteBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#f87171",
    backgroundColor: "#fee2e2",
  },
  deleteBtnText: { color: "#b91c1c", fontWeight: "600", textAlign: "center" },
  callBtn: { backgroundColor: "#1E90FF", padding: 12, borderRadius: 10 },
  chatBtn: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  chatProfileHeader: { alignItems: "center", paddingTop: 20, paddingBottom: 8 },
  chatProfileName: { fontSize: 18, fontWeight: "700", marginBottom: 4 },
  chatBody: { padding: 16 },
  chatEmptyText: { textAlign: "center", color: "#9ca3af", marginVertical: 20 },
  bubbleRow: { flexDirection: "row", alignItems: "flex-end", marginBottom: 10 },
  friendBubbleRow: { justifyContent: "flex-start" },
  myBubbleRow: { justifyContent: "flex-end" },
  bubble: { padding: 10, borderRadius: 16, maxWidth: "75%" },
  friendBubble: { backgroundColor: "#f3f4f6", marginLeft: 8 },
  myBubble: { backgroundColor: "#1E90FF", marginLeft: 8 },
  bubbleText: { color: "#111" },
  avatarTiny: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarTinyText: { fontWeight: "700" },
  chatComposer: {
    padding: 8,
    borderTopWidth: 1,
    borderColor: "#eee",
    flexDirection: "row",
    alignItems: "center",
  },
  colorPickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  colorSwatch: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 2,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  colorSwatchSelected: {
    borderColor: "#111",
  },
  colorSwatchText: {
    color: "#111",
    fontWeight: "700",
  },
  personalityButton: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  personalityText: { fontWeight: "600", color: "#111" },
  dropdownList: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    padding: 8,
    marginTop: 4,
    backgroundColor: "#fff",
  },
  dropdownItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  dropdownItemActive: {
    backgroundColor: "#0A84FF",
  },
  dropdownItemText: {
    color: "#111",
  },
  dropdownItemTextActive: {
    color: "#fff",
    fontWeight: "600",
  },
  primaryBtnFull: {
    marginTop: 20,
    alignSelf: "center",
    minWidth: 50,
  },
  // formActionColumn: {
  //   width: "100%",
  //   alignItems: "center",
  // },
  formActionRow: {
    flexDirection: "row",
    justifyContent: "center", // 가운데 정렬
    alignItems: "center",
    marginTop: 24,
    width: "100%",
  },

  actionBtn: {
    marginHorizontal: 8, // 버튼 사이 간격
    minWidth: 120, // 버튼 너비 적당히
  },

  primaryBtn: {
    backgroundColor: "#F2C94C",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    marginTop: 0,
    alignItems: "center",
    justifyContent: "center",
  },
});
